[package]
name = "ray-tracer-challenge"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "clock"

[[bin]]
name = "sphere"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
png = "0.17.16"

[dev-dependencies]
assert_float_eq = "1.1.4"
indoc = "2.0.6"
